modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL = "https://github.com/Incendo/cloud-forge/issues"
showAsResourcePack = false

[[mods]]
modId = "cloud"
version = "$version"
displayName = "Cloud Command Framework"
displayURL = "https://github.com/Incendo/cloud-forge"
authors = "Cloud Contributors"
description = "Cloud Command Framework on Forge"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.cloud]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloud]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
